### ISSUE TITLE
Need to remove redundancy & old files from Spanish subrepo.

### ISSUE THREAD

**Issue by Sduibek** [Sduibek/Fallout-Fixt-localization#1]
There are 3 other copies of Spanish files besides the most recent translation. Blame Sduibek, I'm sorry. I didn't realize I had multiple copies of stuff in my Dropbox.

NOTE: Lately I've been using Beyond Compare for folder comparisons, I find it's working better than FolderMatch for me. If there's files with identical contents but different dates, it confuses FolderMatch.

The most recent translation is in the "_Female" and "_Male" folders.

These copies have all been included for the sake of completeness 'just in case'.

Thank you.

**Comment by Sduibek** [comment]
Closing for now. @Luffier Removed all but a few of the Spanish/ES files, so presumably he's taking care of this. Thank you @Luffier :)

**Comment by Luffier** [comment]
Indeed, I'll upload the new files in a couples of minutes. No v.7 for the moment though.
